config/routes.rb
Bpgc::Application.routes.draw do

  get '/rebus' => "rebus#index"
  get '/rebus/game' => "rebus#game"
  post '/rebus/answer' => "rebus#check_answer"
  get '/rebus/test' => "rebus#test_rebus"
  get '/rebus/skip' => "rebus#skip_question"
  get '/rebus/leaderboard' => "rebus#leaderboard"
  
  get "cms/rebus" => "cms_rebus#index", as: :cms_rebus
  get "cms/rebuss" => "cms_rebus#show", as: :cms_rebus_show
  post "cms/rebus" => "cms_rebus#save", as: :cms_rebus_save
  put "cms/rebus" => "cms_rebus#update", as: :rebus_update
  delete "cms/rebus/:round" => "cms_rebus#delete", as: :rebus_delete

  get "cms/sponsor" => "cms_sponsor#index", as: :sponor
  get "cms_sponsor/save"
  get "cms_sponsor/show"
  get "cms_sponsor/update"
  get "cms_sponsor/delete"
  get "cms_sponsor/file_upload"

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users,controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end
  get "cms/" => "cms_main#index", as: :dash
  get "cms/registrations" => "cms_main#viewreg", as: :viewreg
  get "cms/change_payment/:id" => "cms_main#changepayment", as: :changepayment
  post "cms/registrations" => "cms_main#viewreg", as: :viewreg_post
  post "cms/regxls" => "cms_main#viewxls", as: :viewxls_post
  get "cms/regxls" => "cms_main#viewxls", as: :viewxls
  get "cms/menu" => "cms_main#menu", as: :menu
  post 'cms/menu' => 'cms_main#save_menu', as: :save_menu
  delete 'cms/menu/:id' => 'cms_main#delete_menu', as: :delete_menu
  delete "cms/delete_reg/:id" => 'cms_main#delete_reg', as: :delete_reg

  get 'cms/piambassador' => 'cms_main#piambassador', as: :cms_piambassador
  get 'cms/viewpi/:referralid' => 'cms_main#viewpi', as: :cms_viewpi
  
  get "cms/settings" => "cms_settings#index", as: :settings_cms
  get "cms/setting" => "cms_settings#show", as: :settings_show

  get "cms/category" => "cms_category#index", as: :category_cms
  post "cms/category" => "cms_category#save", as: :category_save
  get "cms/categories" => "cms_category#show", as: :category_show
  post "cms/category/url" => "cms_category#checkurl", as: :category_url
  get "cms_category/update"
  delete "cms/category/:id" => "cms_category#delete", as: :category_delete

  get "cms/workshop" => "cms_workshop#index", as: :workshop_cms
  post "cms/workshop" => "cms_workshop#save", as: :workshop_save
  get "cms/workshops" => "cms_workshop#show", as: :workshop_show
  get "cms/workshops/:id" => 'cms_workshop#show', as: :workshop
  delete "cms/workshop/:id" => "cms_workshop#delete", as: :workshop_delete
  put "cms/workshop" => 'cms_workshop#update', as: :workshop_update
  post 'cms/workshop/url' => 'cms_workshop#checkurl', as: :workshop_url
  post 'cms/workshops/file' => 'cms_workshop#file_upload', as: :workshop_file

  get "cms/sponsor" => "cms_sponsor#index", as: :sponsor_cms
  post "cms/sponsor" => "cms_sponsor#save", as: :sponsor_save
  get "cms/sponsors" => "cms_sponsor#show", as: :sponsor_show
  delete "cms/sponsor/:id" => "cms_sponsor#delete", as: :sponsor_delete
  get "cms_sponsor/file_upload"

  get "cms/slider" => "cms_slider#index", as: :slider_cms
  post "cms/slider" => "cms_slider#save", as: :slider_save
  get "cms/sliders" => "cms_slider#show", as: :slider_show
  delete "cms/slider/:id" => "cms_slider#delete", as: :slider_delete
  get "cms_slider/file_upload"

  get "main/index"
  get "main/home"
  get "main/updates" => 'main#updates', as: :main_update
  get "main/slides" => 'main#slides', as: :main_slide
  get "main/sponsors" => 'main#sponsors', as: :main_sponsor
  get "main/category" => 'main#category', as: :main_category
  get "main/menu" => 'main#menu', as: :main_menu
  post "main/saveprofile" => 'main#saveprofile', as: :main_saveprofile
  get "main/getprofile" => 'main#getprofile', as: :main_getprofile
  post "main/getregistration" => 'main#getregistration', as: :main_getregistration
  get "/referral/:referralid" => 'main#referral', as: :main_referral

  get "cms/page" => 'cms_page#index', as: :page_cms
  get "cms/pages" => 'cms_page#show', as: :pages
  get "cms/page/:id" => 'cms_page#show', as: :page
  post "cms/page" => 'cms_page#save', as: :page_save
  put "cms/page" => 'cms_page#update', as: :page_update
  delete "cms/page/:id" => 'cms_page#delete', as: :page_delete
  post "cms/page/url" => "cms_page#checkurl", as: :page_url

  get "cms/update" => 'cms_update#index', as: :update_cms
  get "cms/updates" => 'cms_update#show', as: :updates
  get "cms/update/:id" => 'cms_update#show', as: :update
  post "cms/update" => 'cms_update#save', as: :update_save
  put "cms/update" => 'cms_update#update', as: :update_update
  delete "cms/update/:id" => 'cms_update#delete', as: :update_delete

  get "cms/event" => 'cms_event#index', as: :event_cms
  get "cms/events" => 'cms_event#show', as: :events
  
  get "cms/events/:id" => 'cms_event#show', as: :event
  post "cms/event" => 'cms_event#save', as: :event_save
  put "cms/event" => 'cms_event#update', as: :event_update
  delete "cms/event/:id" => 'cms_event#delete', as: :event_delete
  get 'manage/user' => 'manageuser#index', as: :user_index
  get 'manage/user/list' => 'manageuser#show' 
  put 'manage/user/update' => 'manageuser#update'
  delete 'manage/user/delete/:id' => 'manageuser#delete'
  get 'manage/user/:id' => 'manageuser#assign'

  post 'cms/event/url' => 'cms_event#checkurl', as: :event_url
  post 'cms/events/file' => 'cms_event#file_upload', as: :event_file

  get '/profile' => 'main#profile', as: :profile

  get ':id0'=>'main#page', as: :get_page_0
  get ':id0/:id1'=>'main#page', as: :get_page_1
  get ':id0/:id1/:id2'=>'main#page', as: :get_page_2
  get ':id0/:id1/:id2/:id3'=>'main#page', as: :get_page_3
  get ':id0/:id1/:id2/:id3/:id4'=>'main#page', as: :get_page_4
  get ':id0/:id1/:id2/:id3/:id4/:id5'=>'main#page', as: :get_page_5
  get ':id0/:id1/:id2/:id3/:id4/:id5/:id6'=>'main#page', as: :get_page_6
  get ':id0/:id1/:id2/:id3/:id4/:id5/:id6/:id7'=>'main#page', as: :get_page_7
  
  

  root 'main#index'

  

end

app/controllers/cms_main_controller.rb
class CmsMainController < ApplicationController
  require 'csv'
  layout "layouts/cms"

  before_filter :authenticate_user!
  authorize_resource :class => CmsMainController

  def index
  	@event = Event.count
  	@workshop = Workshop.count
  	@user = User.count
  	#@sponsor =  Sponsor.count
  end

  def dash
  end

  def menu
  	@menus = Menu.all.order(order: :asc)
  	@top_menu = Menu.where(parent_id: nil).order(order: :asc)
  	@maps = Map.all

  end

  def save_menu
  	menu = Menu.new
  	menu.title = params[:title]
  	menu.url = params[:url]
  	menu.parent_id = params[:parent_id]
    menu.level = params[:level]
    menu.category = params[:category]
    menu.order = params[:order]
  	if menu.save
  		flash[:notice] = 'Menu added'
  		redirect_to menu_path and return
  	else
  		flash[:alert] = 'There was a problem..sorry'
  		redirect_to menu_path and return
  	end
  end

  def delete_menu
  	menu = Menu.find(params[:id]).delete
  	flash[:notice] = 'Menu Deleted'
  	redirect_to menu_path and return
  end

  def viewreg
   
   @all_events = Event.all
   @all_workshops = Workshop.all

   @paramscategory = params[:category] || ""
   @paramsid = params[:id] || ""

      if request.post?
        if params[:category] == "event"
          if params[:id].nil?
            @reg = Registration.where(category: params[:category])
          else
            @reg = Registration.where(category: params[:category],item_id: params[:id])
          end
        elsif params[:category] == "workshop"
          if params[:id].nil?
            @reg = Registration.where(category: params[:category])
          else
            @reg = Registration.where(category: params[:category],item_id: params[:id])
          end
        end
      else
        @reg = Registration.all
      end
 

  end

  def viewxls
    @all_events = Event.all
   @all_workshops = Workshop.all

   @paramscategory = params[:category] || ""
   @paramsid = params[:id] || ""

      if request.post?
        if params[:category] == "event"
          if params[:id].nil?
            @reg = Registration.where(category: params[:category])
          else
            @reg = Registration.where(category: params[:category],item_id: params[:id])
          end
        elsif params[:category] == "workshop"
          if params[:id].nil?
            @reg = Registration.where(category: params[:category])
          else
            @reg = Registration.where(category: params[:category],item_id: params[:id])
          end
        end
      else
        @reg = Registration.all
      end
      
    respond_to do |format|
      format.xls
    end
  end

  def delete_reg
    registration = Registration.find(params[:id])

    if registration.delete
      redirect_to :viewreg
    end

  end

  def changepayment
    registration = Registration.find(params[:id])

    registration.payment = "paid"
    
    if registration.save
        redirect_to :viewreg
    end
  end


  def piambassador
    @amb = Profile.where(piamb: 1)
  end

  def viewpi
    @subuser = Profile.where(referralid: params[:referralid])
  end
end

app/helpers/cms_main_helper.rb
module CmsMainHelper
end

app/views/cms_main/dash.html.erb
<h1>CmsMain#dash</h1>
<p>Find me in app/views/cms_main/dash.html.erb</p>

app/views/cms_main/index.html.erb
<div class='container'>
	<div class="row">
		<div class='col-md-3 info-column'>
			<%= @event || 0 %> <span>Events</span>
		</div>

		<div class='col-md-3 info-column'>
			<%= @user || 0 %> <span>Users</span>
		</div>

		<div class='col-md-3 info-column'>
			<%= @workshop || 0  %> <span>Workshops</span>
		</div>

		<div class='col-md-3 info-column'>
			<%= @sponsor || 0 %> <span>Sponsors</span>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12"><h1>Marketing</h1></div>
		<div class="col-md-3 info-column">
			<%= Profile.where(how: "1").count %> <span>Social Media</span>
		</div>
		<div class="col-md-3 info-column">
			<%= Profile.where(how: "2").count %> <span>Friends</span>
		</div>
		<div class="col-md-3 info-column">
			<%= Profile.where(how: "3").count %> <span>PI Ambassador</span>
		</div>
		<div class="col-md-3 info-column">
			<%= Profile.where(how: "4").count %> <span>College Administration</span>
		</div>
		<div class="col-md-3 info-column">
			<%= Profile.where(how: "5").count %> <span>PI Marketing Volunteers</span>
		</div>
	</div>
</div>

app/views/cms_main/menu.html.erb
<div class='container'>

	
    <%= form_tag save_menu_path , method: :post , :class => 'form-horizontal'  %>
	  <div class="form-group">

	    <label for="inputEmail3" class="col-sm-2 control-label">Title</label>
	    <div class="col-sm-10">
	      <input type="text" name='title' class="form-control" id="inputEmail3" placeholder="Event / Workshop" required>
	    </div>
	  </div>
	  <div class="form-group">
	    <label for="inputPassword3" class="col-sm-2 control-label">URL</label>
	    <div class="col-sm-10">
	     <select class="form-control" name='url'>
	      	  <option value=''>None</option>
			  <option value="/">/</option>
	      	  <% @maps.each do |map| %>	
			  <option value="<%= map.url %>"><%= map.url %></option>
			  <% end %>
			</select>
	    </div>
	  </div>

	  <div class="form-group">
	    <label for="inputPassword3" class="col-sm-2 control-label">Parent</label>
	    <div class="col-sm-10">
	      
	      	<select class="form-control" name='parent_id'>
	      	  <option value=''>None</option>
	      	  <% @menus.each do |menu| %>	
			  <option value="<%= menu.id %>"><%= menu.backtrack if menu.parent %><%= menu.title %></option>
			  <% end %>
			</select>
	    </div>
	  </div>

	  <div class="form-group">
	    <label for="inputPassword3" class="col-sm-2 control-label">Level</label>
	    <div class="col-sm-4">
	      
	      	<select class="form-control" name='level'>
	      	  <option value='' disabled selected="selected">None</option>
			  <option value="1">Top</option>
			  <option value="2">Middle</option>
			  <option value="3">Bottom</option>
			</select>
	    </div>
	    <div class="col-sm-4">
	      
	      	<select class="form-control" name='category'>
	      	  <option value='' disabled selected="selected">None</option>
			  <option value="home">Home</option>
			  <option value="event">Event</option>
			  <option value="workshop">Workshop</option>
			  <option value="sponsor">Sponsor</option>
			  <option value="proshow">Proshow</option>
			  <option value="hospitality">Hospitality</option>
			  <option value="about">About</option>
			  <option value="contact">Contact</option>
			</select>
	    </div>
	     <div class="col-sm-2">
	      
	      	<input type='number' name='order' placeholder = 'Order' class='form-control'>
	    </div>
	  </div>
			  
	  <div class="form-group">
	    <div class="col-sm-offset-2 col-sm-10">
	      <button type="submit" class="btn btn-primary">Add Menu</button>
	    </div>
	  </div>
	</form>
	<hr>
	<div class="panel panel-default">
	  <div class="panel-heading">
	    List of Menu Items
	  </div>
	  <div class="panel-body">
	    <table class='table table-striped'>
		<thead>
			<tr>
				<td>Title</td>
				<td>URL</td>
				<td>Category</td>
				<td>Level</td>
				<td>Order</td>
				<td>Action</td>
			</tr>
		</thead>
		<% @menus.each do |menu| %>
			<tr>
				<td><%= menu.title %></td>
				<td><%= menu.url %></td>
				<td><%= menu.category %></td>
				<td><%= menu.level %></td>
				<td><%= menu.order %></td>
				<td><%= link_to 'Delete',delete_menu_url(menu.id), method: :delete, :class => 'btn btn-xs btn-default' %></td>
			</tr>
		<% end %>
	</table>
	  </div>
	</div>
	
	<hr>
	<h4>Hierarchy</h4>
	<% @top_menu.each do |menu| %>
    <div class='top_menu'>
		 <%= menu.title  %> ( <%= menu.url %> ) <%= link_to 'Delete',delete_menu_url(menu.id), method: :delete, :class => 'btn btn-xs btn-default' %>
		 <% menu.sub_menus.each do |sub_menu| %>
		 <div class='sub_menu'><%= sub_menu.title %> ( <%= sub_menu.url %> ) <%= link_to 'Delete',delete_menu_url(sub_menu.id), method: :delete, :class => 'btn btn-xs btn-default' %>
		 	<% sub_menu.sub_menus.each do |sub_sub_menu| %>
		 		<div class='sub_sub_menu'>
		 			<%= sub_sub_menu.title %>( <%= sub_sub_menu.url %> ) <%= link_to 'Delete',delete_menu_url(sub_sub_menu.id), method: :delete, :class => 'btn btn-xs btn-default' %>
		 		</div> 
		 	<% end %>
		 </div>		 
		 <% end %><hr>
	</div>
	<% end %>
</div>

app/views/cms_main/piambassador.html.erb
<table class="table table-hover">
	<thead>
		<tr>
			<th>PID</th>
			<th>Name</th>
			<th>College</th>
			<th>Year</th>
			<th>Contact</th>
			<th>Count</th>
			<th>Action</th>
		</tr>
	</thead>	
	<tbody>
	<% @amb.each do |a| %>
		<tr>
			<td><%= a.pinnacleid %></td>
			<td><%= a.name %></td>
			<td><%= a.institution %></td>
			<td><%= a.year %></td>
			<td><%= a.phonenumber %> / <%= a.user.email %></td>
			<td><%= Profile.where(referralid: a.pinnacleid).count %></td>
			<td><a href="/cms/viewpi/<%= a.pinnacleid %>">View Users</a></td>
		</tr>
	<% end %>
	</tbody>
</table>

app/views/cms_main/viewpi.html.erb
<div class="col-md-3 info-column">
		<%= @subuser.count %> <span>Users</span>
</div>
<table class="table table-hovers">
	<thead>
		<tr>
			<th>PID</th>
			<th>Name</th>
			<th>Course</th>
			<th>Branch</th>
			<th>Institution</th>
			<th>Contact</th>
			<th>Year</th>
		</tr>
	</thead>
	<tbody>
	<% @subuser.each do |s| %>
		<tr>
			<td><%= s.pinnacleid %></td>
			<td><%= s.name %></td>
			<td><%= s.course %></td>
			<td><%= s.branch %></td>
			<td><%= s.institution %></td>
			<td><%= s.phonenumber %>/<%= s.user.email %></td>
			<td><%= s.year %></td>
		</tr>
	<% end %>
	</tbody>
</table>

app/views/cms_main/viewreg.html.erb
<div class="row col-md-12">
	<div class="col-md-6 info-box">
		<%= form_tag('/cms/registrations',method: :post) do %>
			<div class="form-group">
				<label>Events</label>
				<input type="hidden" name="category" value="event">
				<select name="id" class="form-control">
					<% @all_events.each do |e| %>
						<option value = '<%= e.id %>'><%= e.name %></option>
					<% end %>
				</select>
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-primary">Search</button>
			</div>
		<% end %>
	</div>
	<div class="col-md-6 info-box">
		<%= form_tag('/cms/registrations',method: :post) do %>
			<div class="form-group">
				<label>Workshops</label>
				<input type="hidden" name="category" value="workshop">
				<select name="id" class="form-control">
					<% @all_workshops.each do |e| %>
						<option value = '<%= e.id %>'><%= e.name %></option>
					<% end %>
				</select>
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-primary">Search</button>
			</div>
		<% end %>
	</div>
</div>

<div class="row col-md-12">
<table class="table table-hover">
	<thead>
		<tr>
			<th>S.No.</th>
			<th>PID</th>
			<th>CATEGORY</th>
			<th>EVENT/WORKSHOP</th>
			<th>NAME</th>
			<th>EMAIL</th>
			<th>PHONENUMBER</th>
			<th>BRANCH</th>
			<th>COURSE</th>
			<th>YEAR</th>
			<th>INSTITUTION</th>
			<th>OTHERS</th>
			<th>PAYMENT</th>
			<th>DELETE</th>
		</tr>
	</thead>
	<tbody>
	<% i = 1 %>
	<% @reg.each do |r| %>
		<tr>
			<td><%= i %></td>
			<td><%= r.user.profile.pinnacleid %></td>
			<td><%= r.category %></td>
			<td><% if r.category == "event" %> <%= Event.find(r.item_id).name %> <% else %> <%= Workshop.find(r.item_id).name %> <% end %></td>
			<td><%= r.user.profile.name %></td>
			<td><%= r.user.email %></td>
			<td><%= r.user.profile.phonenumber %></td>
			<td><%= r.user.profile.branch %></td>
			<td><%= r.user.profile.course %></td>
			<td><%= r.user.profile.year %></td>
			<td><%= r.user.profile.institution %></td>
			<td><%= r.details %></td>
			<td><% if ((r.payment != "paid") && (r.category == "workshop"))%><%= form_tag("/cms/change_payment/#{r.id}",method: :get) do %><button class = "btn btn-primary">Paid</button><% end %><% end %></td>
			<td><%= form_tag("/cms/delete_reg/#{r.id}", method: :delete) do %><button class = "btn btn-danger">Delete</button><% end %></td>

		</tr>
	<% i = i+1 %>
	<% end %>
	</tbody>
</table>
</div>
<div class="row col-md-12">
	<%= form_tag('/cms/regxls.xls',method: :post) do %>	
	<input type = "hidden" name = 'category' value="<%= @paramscategory %>"/>
	<input type = "hidden" name = 'id' value="<%= @paramsid %>"/>
	<button type = "submit" class = "btn btn-primary">Download XLS</a>
	<% end %>
</div>

<!-- <div ng-controller = "mainController" class = "col-md-12">
 
<%= form_tag('/cms/registrations/',method: :post) do %>
<div class = "dropdown">
<select name = "category" ng-model = "DropdownChoice" ng-change = "DropdownSelect()">
<option value = "all">All</option>
<option value = "events">Events</option>
<option value = "workshops">Workshops</option>
</select>
</div>

<div class = "dropdown" ng-show = "EventShow">
<select name = 'event' ng-model = "SelectedEvent">
<option selected="selected" value = "none" disabled = "disabled">Select one</option>
<option value = 'all_events'>All Events</option>
<% @all_events.each do |e| %>
<option value = '<%= e.id %>'><%= e.name %></option>
<% end %>
</select>
</div>

<div class = "dropdown" ng-show = "WorkshopShow">
<select name = 'workshop'>
<option selected="selected" value = "none" disabled = "disabled">Select one</option>
<option value = 'all_workshops'>All Workshops</option>
<% @all_workshops.each do |e| %>
<option value = '<%= e.id %>'><%= e.name %></option>
<% end %>
</select>

</div>

<button type = "submit">Show</button>
<% end %>

<table class="table table-hover">
	<thead>
		<tr>
			<th>S.No.</th>
			<th>PID</th>
			<th>CATEGORY</th>
			<th>EVENT/WORKSHOP</th>
			<th>NAME</th>
			<th>EMAIL</th>
			<th>PHONENUMBER</th>
			<th>BRANCH</th>
			<th>COURSE</th>
			<th>YEAR</th>
			<th>INSTITUTION</th>
		</tr>
	</thead>
	<tbody>
	<% i = 1 %>
	<% @reg.each do |r| %>
		<tr>
			<td><%= i %></td>
			<td><%= r.user.profile.pinnacleid %></td>
			<td><%= r.category %></td>
			<td><% if r.category == "event" %> <%= Event.find(r.item_id).name %> <% else %> <%= Workshop.find(r.item_id).name %> <% end %></td>
			<td><%= r.user.profile.name %></td>
			<td><%= r.user.email %></td>
			<td><%= r.user.profile.phonenumber %></td>
			<td><%= r.user.profile.branch %></td>
			<td><%= r.user.profile.course %></td>
			<td><%= r.user.profile.year %></td>
			<td><%= r.user.profile.institution %></td>
		</tr>
	<% i = i+1 %>
	<% end %>
	</tbody>
</table>

<div class="row">
	<%= form_tag('/cms/regxls.xls',method: :post) do %>	
	<input type = "hidden" name = 'category' ng-model = "DropdownChoice"/>
	<input type = "hidden" name = 'category' ng-model = "SelectedEvent"/>
	<input type = "hidden" name = 'category' ng-model = "SelectedWorkshop"/>
	<button type = "submit" class = "btn btn-primary">Download XLS</a>
	<% end %>
</div>

</div> -->

app/views/cms_main/viewxls.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
         <Cell><Data ss:Type="String">S.No.</Data></Cell>
       <Cell><Data ss:Type="String">PID</Data></Cell>
       <Cell><Data ss:Type="String">CATEGORY</Data></Cell>
       <Cell><Data ss:Type="String">EVENT/WORKSHOP</Data></Cell>
       <Cell><Data ss:Type="String">NAME</Data></Cell>
       <Cell><Data ss:Type="String">EMAIL</Data></Cell>
       <Cell><Data ss:Type="String">PHONENUMBER</Data></Cell>
       <Cell><Data ss:Type="String">BRANCH</Data></Cell>
         <Cell><Data ss:Type="String">COURSE</Data></Cell>
         <Cell><Data ss:Type="String">YEAR</Data></Cell>
         <Cell><Data ss:Type="String">INSTITUTION</Data></Cell>
         <Cell><Data ss:Type="String">PAYMENT</Data></Cell>
      </Row>
      <% i = 1 %>
   <% @reg.each do |r| %>
      <Row>
        <Cell><Data ss:Type="String"><%= i %></Data></Cell>
      <Cell><Data ss:Type="String"><%= r.user.profile.pinnacleid %></Data></Cell>
      <Cell><Data ss:Type="String"><%= r.category %></Data></Cell>
      <Cell><Data ss:Type="String"><% if r.category == "event" %> <%= Event.find(r.item_id).name %> <% else %> <%= Workshop.find(r.item_id).name %> <% end %></Data></Cell>
      <Cell><Data ss:Type="String"><%= r.user.profile.name %></Data></Cell>
      <Cell><Data ss:Type="String"><%= r.user.email %></Data></Cell>
      <Cell><Data ss:Type="String"><%= r.user.profile.phonenumber %></Data></Cell>
      <Cell><Data ss:Type="String"><%= r.user.profile.branch %></Data></Cell>
      <Cell><Data ss:Type="String"><%= r.user.profile.course %></Data></Cell>
      <Cell><Data ss:Type="String"><%= r.user.profile.year %></Data></Cell>
      <Cell><Data ss:Type="String"><%= r.user.profile.institution %></Data></Cell>
      <Cell><Data ss:Type="String"><%= r.payment %></Data></Cell>
      </Row>
      <% i = i+1 %>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>